server:
  port:
    9000
spring:
  datasource:
    url:
      jdbc:postgresql://localhost:5432/postgres
#      jdbc:postgresql://192.168.1.0:5432/postgres
    username:
      postgres
    password:
      root
    driver-class-name:
      org.postgresql.Driver
  jpa:
    database-platform:
      org.hibernate.dialect.PostgreSQLDialect
    show-sql:
      true
    hibernate:
      ddl-auto:
#        create
        none
  liquibase:
    change-log:
      classpath:/db/changelog/dbchangelog.xml
  sql:
    init:
      mode:
#        always
        never